### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by scopatz**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
Hey @conda-forge/expat maintainers, I have added myself here and done a simple rerender.  There are a lot of weird failures, Mac and Linux succeed. All I need is Linux, because the other packages are behind the old epoch cf201901 label.  Is there any chance that this could get merged, please?

**Comment by scopatz** [comment]
Also note that ppc and aarch have modern builds already, so they don't need to pass.

**Comment by scopatz** [comment]
OK! I have ppc and aarch working again.

**Comment by scopatz** [comment]
And actually the windows issues on Azure seem to be because of the vc version, but this does run on appveyor.  So I think this is good to go! Ping @kwilcox @mingwandroid @msarahan @ocefpaf @pelson

**Comment by scopatz** [comment]
Merging since I am adding myself and it has been a day

**Comment by ocefpaf** [comment]
> Merging since I am adding myself and it has been a day

Sorry. It was a holiday here yesterday and I'm still catching up with the botifications.

**Pull request merged**
